---
title: "Examining Air Pollution and Environmental Factors"
subtitle: "Kiana Fields, Julian Jacklin, Prasiddhi Thapaliya, Omar Youssif"
format: html
editor: visual
---

# Write-up

## Introduction:

We are using data from the United States Environmental Protection Agency (EPA). Their tool provides daily records of air pollutant concentrations of various atmospheric pollutants. This can be filtered by geographic area such as state, city, county, or specific monitoring site. The typical units for each pollutant, depending on its abundance in the air, is either in ppm (parts per million), ppb (parts per billion), or µg/m^3^ (micrograms per cubic meter).

For our research, we narrowed our focus on the Portland-Hillsboro-Vancouver area to analyze changes in pollutant concentration and thus air quality. We looked at the following atmospheric compounds: CO (carbon monoxide), NO2 (nitrogen dioxide), O3 (ozone), PM2.5 (fine particulate matter), and SO2 (sulfur dioxide). We chose these because they are the most abundant and seem to be the most talked about greenhouse gases among the general population.

### Question 1: Effects of COVID on Air Quality

#### Introduction (1-2 paragraphs):

COVID-19 and it's effects have impacted us all. As with any pandemic, the primary concerns worldwide were largely related to public health and economic welfare. Like many other nations, the U.S met the the concerns of the former, by enacting state-by-state quarantines ("stay-at-home" orders). Subsequently, major metropolitan centers in the nation characterized by greater motor-vehicle traffic, experienced a dramatic dip in commuter density as quarantine mandates went into effect and drastically fewer commuters had to drive to work each day. One impact of COVID-19 that has yet to be discussed as severely as the others, is its impact on our climate; particularly, on air quality. A popular assumption, is that air quality improved during this time, as less commuters were "on the road", and so less vehicles were used and emitting pollutants. We are interested in exploring this assumption by analyzing the concentration levels of major pollutants produced by motor-vehicles (namely, the variables PM2.5, SO2, NO2, CO, and Ozone), before, during, and after quarantine, using our chosen dataset.

#### Approach (1-2 paragraphs):

Our underlying hypothesis is that fewer pollutants were emitted into the atmosphere in Portland from March 2020 - June 2021 (span of Oregon state quarantine mandate). Our dataset offers average pollutant concentrations by month, over several years (Jan 2017 - Dec 2023). In our first graph we have chosen to focus on PM2.5 concentrations over this 7-year window, since this is the most hazardous and prominent pollutant that motor-vehicles emit. Additionally, we'd like to observe its trends in recent history, through the quarantine, and afterward, to identify any contrasts. We are visualizing this data by a column graph such that each column is a month, sectioned by color and year, with markers indicating the beginning and end of Oregon's quarantine. Our second graph (a collection of three plots) explores concentration trends by the other pollutants, over each year in the immediate window around quarantine (2019, 2020, 2021). This is done via a trend line, overlayed by columns to distinguish monthly concentrations readings. Both of these plots help us better visualize trends in major pollutant concentrations over time.

#### Analysis (2-3 code blocks, 2 figures, text/code comments as needed):

In this section, provide the code that generates your plots. Use scale functions to provide nice axis labels and guides. You are welcome to use theme functions to customize the appearance of your plot, but you are not required to do so. All plots must be made with ggplot2. Do not use base R or lattice plotting functions.

```{r graph 1 echo=FALSE, fig.width=8}
#FIRST GRAPH








 
  
```

#### Discussion (1-3 paragraphs):

In the Discussion section, interpret the results of your analysis. Identify any trends revealed (or not revealed) by the plots. Speculate about why the data looks the way it does.

### Question 2: Wildfire Season and Air Quality

The intensity of Oregon's wildfire season in Oregon has increased over time as a result of historical forest management as well as climate change effects. The intensity of these fires is of concern to public safety both immediately in fire prone areas as well as for communities facing decreased air quality from smoke. We are interested in exploring this aspect of the issue of wildfires by analyzing concentration levels of major pollutants produced by wildfires (particularly PM2.5, NO2, Ozone and general AQI) before during and after fire season.
